---
#
# Check whether EMs event data is present.
#

- name: "Check event"
  manageiq_automate:
    workspace: "{{ workspace }}"
    attribute_exists:
      object: root
      attribute: event_stream
  register: check_event
